name: Rust
on: [push]

jobs:
  build-linux-x64:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        run: cargo clean && cargo build --release --target=x86_64-unknown-linux-gnu && strip target/x86_64-unknown-linux-gnu/release/rexetool && mv target/x86_64-unknown-linux-gnu/release/rexetool target/x86_64-unknown-linux-gnu/release/rexetool_linux_x64

      - name: Upload linux-amd64
        uses: actions/upload-artifact@v2
        with: 
          name: rexetool_linux_x64
          path: target/x86_64-unknown-linux-gnu/release/rexetool_linux_x64
          
      - name: Build x86
        run: cargo clean && cargo build --release --target=i686-unknown-linux-gnu && strip target/i686-unknown-linux-gnu/release/rexetool && mv target/i686-unknown-linux-gnu/release/rexetool target/i686-unknown-linux-gnu/release/rexetool_linux_x86

      - name: Upload linux-x86
        uses: actions/upload-artifact@v2
        with: 
          name: rexetool_linux_x86
          path: target/i686-unknown-linux-gnu/release/rexetool_linux_x86

  build-win-x64:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        run: |
          cargo clean
          cargo build --release
      - name: Upload win-x64
        uses: actions/upload-artifact@v2
        with: 
          name: rexetool_win_x64.exe
          path: target/release/rexetool.exe

      - name: Build
        run: |
          cargo clean
          rustup target install i686-pc-windows-msvc
          cargo build --release --target=i686-pc-windows-msvc
          
      - name: Upload win-x64
        uses: actions/upload-artifact@v2
        with: 
          name: rexetool_win_x86.exe
          path: target/i686-pc-windows-msvc/release/rexetool.exe
          
  build-mac-x64:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-apple-darwin
          default: true
          override: true

      - name: Build for mac
        run: cargo clean && cargo build --release && strip target/release/rexetool && mv target/release/rexetool target/release/rexetool_mac_x64

      - name: Upload mac-x64
        uses: actions/upload-artifact@v2
        with: 
          name: rexetool_mac_x64.exe
          path: target/release/rexetool_mac_x64
