name: Rust
on: [push]

jobs:
  build-linux-x64:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        run: rustup toolchain install nightly && rustup component add rust-src --toolchain nightly && cargo clean && cargo +nightly build -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort --target x86_64-unknown-linux-gnu --release && strip target/x86_64-unknown-linux-gnu/release/rexetool && mv target/x86_64-unknown-linux-gnu/release/rexetool target/x86_64-unknown-linux-gnu/release/rexetool_linux_x64

      - name: Upload linux-amd64
        uses: actions/upload-artifact@v2
        with: 
          name: rexetool_linux_x64
          path: target/x86_64-unknown-linux-gnu/release/rexetool_linux_x64
          
  build-win-x64:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        run: |
          rustup toolchain install nightly
          rustup component add rust-src --toolchain nightly
          cargo clean
          cargo +nightly build -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort --target x86_64-pc-windows-msvc --release
      - name: Upload win-x64
        uses: actions/upload-artifact@v2
        with: 
          name: rexetool_win_x64.exe
          path: target/x86_64-pc-windows-msvc/release/rexetool.exe

      - name: Build
        run: |
          rustup toolchain install nightly
          rustup component add rust-src --toolchain nightly
          cargo clean
          rustup target install i686-pc-windows-msvc
          cargo +nightly build -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort --target i686-pc-windows-msvc --release
          
      - name: Upload win-x64
        uses: actions/upload-artifact@v2
        with: 
          name: rexetool_win_x86.exe
          path: target/i686-pc-windows-msvc/release/rexetool.exe
          
  build-mac-x64:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-apple-darwin
          default: true
          override: true

      - name: Build for mac
        run: rustup toolchain install nightly && rustup component add rust-src --toolchain nightly && cargo clean && cargo +nightly build -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort --target x86_64-apple-darwin --release && strip target/x86_64-apple-darwin/release/rexetool && mv target/x86_64-apple-darwin/release/rexetool target/x86_64-apple-darwin/release/rexetool_mac_x64

      - name: Upload mac-x64
        uses: actions/upload-artifact@v2
        with: 
          name: rexetool_mac_x64.exe
          path: target/x86_64-apple-darwin/release/rexetool_mac_x64
